tests:
  Pages should be fast enough:
    path: /.*
    assertions:
      - main.io < 150ms
      - main.cpu_time < 300ms
  Twig template cache should be enabled in production:
    path: /.*
    unless: 'is_dev()'
    assertions:
      - metrics.twig.compile.count == 0

scenarios:
  Home:
    - /welcome
  Login:
    - /user/login
